### PR TITLE
Added download routines to core.py so files can easily be ket up to date

### PR DESCRIPTION
**Pull request by strawpants**
Note sure, whether it makes sense to create a pull request of a pull request, but I guess this feature may come in handy. 
new (Leap second and eop) files can be downloaded, and preprocessed for further use by calling

```
import pygtide
pt=pygtide.pygtide()
pt.refresh_data()
``` 

R.

### CODE REVIEW

**Comment by trichter** [comment]
Thanks for your PR! I saw it only now, because I was not watching this repository. These refresh methods are very useful. I hesitate to merge, because of the introduction of new dependency on astropy.

**Comment by strawpants** [comment]
I actually forgot about this too. I've now pushed a version which doesn't have the astropy dependency anymore.

**Comment by trichter** [comment]
Thank you! It is working well.

Some more points before I want to merge this:

* You left a breakpoint in the function (`set_trace`)
* Can you rename the raw downloaded files to `[raw]_Leap_Second_History.dat`, `[raw]_finals2000A.dat` and `[raw]_eopc04_IAU2000.dat` (or alternatively rename the functions already inside the repository) so that the old files get overwritten?
* The file `etddt.dat` was not touched. 
* Can you please rebase on top of master? I added a local version modifier indicating that this is a fork.

**Comment by strawpants** [comment]
Ok, I've implemented the changes. This should work now

**Comment by trichter** [comment]
@strawpants Thanks!

**Pull request merged**
